source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '9.0'

target 'Example' do
  use_frameworks!

  # Pods for Example
  pod 'ALCameraViewController'
  pod 'AlamofireImage'
  pod 'AlamofireObjectMapper'
  pod 'KeychainAccess'
  pod 'PKHUD'
  pod 'PullToRefresher'
  pod 'RMUniversalAlert'
  pod 'RealmSwift'
  pod 'SnapKit'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
